JUnit version 4.11-SNAPSHOT-20120416-1530
..E
Time: 0.007
There was 1 failure:
1) the_result_of_one_number_is_itself(StringCalculatorTest)
java.lang.AssertionError: expected:<1> but was:<0>
	at StringCalculatorTest.the_result_of_one_number_is_itself(StringCalculatorTest.java:13)

FAILURES!!!
Tests run: 2,  Failures: 1
